blank_issues_enabled: true
contact_links:
  - name: 🗣 Start a discussion on GitHub
    url: https://github.com/google/iree/discussions
    about: For topics that don't fit into a more specific category
  - name: 📧 Send an email to our mailing list
    url: https://groups.google.com/forum/#!forum/iree-discuss
    about: For topics that don't fit into a more specific category
  - name: 💬 Join us on Discord
    url: https://discord.gg/26P4xW4
    about: For realtime communication with the team and collaborators
