name: User Report
description: Report an issue or ask for help with something
labels: ["help wanted", "awaiting-triage"]
body:
  - type: markdown
    attributes:
      value: |
        :star2: Thanks for taking the time to report this issue! :star2:

        Please search through [other recent issues](https://github.com/google/iree/issues) to see if your report overlaps with an existing issue.

        If you are unsure about what to include in an issue, feel free to reach out using our other [communication channels](https://github.com/google/iree#communication-channels).
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen?

        For compiler errors, we like to see the input IR and the MLIR output leading up to whatever error occurred.
      placeholder: Tell us what you see! Please also copy/paste or link to any relevant log output.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: What component(s) does this issue relate to?
      description: |
        If you're not sure, that's okay! This helps us route issues to the right developers.
      multiple: true
      options:
        - Frontends
        - MLIR
        - Python
        - Compiler
        - Runtime
        - Other
  - type: textarea
    id: version
    attributes:
      label: Version information
      description: What version of our software are you running?
      placeholder: This could be a git commit hash or release version number.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: For example, did what you were trying work before?
