# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI

on:
  pull_request:

env:
  GIT_SSH_COMMAND: "ssh -v"
  GIT_TRACE: 1
  GIT_TRACE_PACKET: 1
  GIT_TRACE_PERFORMANCE: 1

jobs:
  # ------------------------------------------------------------------------- #
  # Standard (small) GitHub-hosted runners
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
  small:
    runs-on: windows-2022
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@ef4381812d7f6ada8d30124c82c14899e3866feb # 3.5.0 + fixes
        with:
          submodules: true
  small_manual_submodules:
    runs-on: windows-2022
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@ef4381812d7f6ada8d30124c82c14899e3866feb # 3.5.0 + fixes
      - name: "Updating git submodules"
        run: git submodule update --init --jobs 8 --depth 1

  small_bash:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@ef4381812d7f6ada8d30124c82c14899e3866feb # 3.5.0 + fixes
        with:
          submodules: true
  small_bash_manual_submodules:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@ef4381812d7f6ada8d30124c82c14899e3866feb # 3.5.0 + fixes
      - name: "Updating git submodules"
        run: git submodule update --init --jobs 8 --depth 1
  # ------------------------------------------------------------------------- #

  # ------------------------------------------------------------------------- #
  # Large GitHub-hosted runners (configured at Organization level)
  # https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners
  large:
    runs-on: windows-2022-64core
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@ef4381812d7f6ada8d30124c82c14899e3866feb # 3.5.0 + fixes
        with:
          submodules: true
  large_manual_submodules:
    runs-on: windows-2022-64core
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@ef4381812d7f6ada8d30124c82c14899e3866feb # 3.5.0 + fixes
      - name: "Updating git submodules"
        run: git submodule update --init --jobs 8 --depth 1

  large_bash:
    runs-on: windows-2022-64core
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@ef4381812d7f6ada8d30124c82c14899e3866feb # 3.5.0 + fixes
        with:
          submodules: true
  large_bash_manual_submodules:
    runs-on: windows-2022-64core
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@ef4381812d7f6ada8d30124c82c14899e3866feb # 3.5.0 + fixes
      - name: "Updating git submodules"
        run: git submodule update --init --jobs 8 --depth 1
