# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI

on:
  pull_request:

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  GIT_SSH_COMMAND: "ssh -v"
  GIT_TRACE: 1
  GIT_TRACE_PACKET: 1
  GIT_TRACE_PERFORMANCE: 1

# TODO(scotttodd): test these
# runs-on: managed-windows-cpu
# actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

jobs:
  checkout_windows_2022:
    runs-on: windows-2022
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
        with:
          submodules: true
  checkout_windows_2022_manual_submodules:
    runs-on: windows-2022
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
      - name: "Updating git submodules"
        run: git submodule update --init --jobs 8 --depth 1

  checkout_windows_2022_bash:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
        with:
          submodules: true
  checkout_windows_2022_bash_manual_submodules:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
      - name: "Updating git submodules"
        run: git submodule update --init --jobs 8 --depth 1
