# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI Test 2
on:
  workflow_call:
  workflow_dispatch:

jobs:
  ci_test_2:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo
        run: echo "Hello world!"
