name: PkgCI core tests
on:
  pull_request:
    paths:
      - ".github/workflows/pkgci_core_tests.yml"
  workflow_dispatch:

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  core_tests:
    runs-on: ubuntu-20.04
    env:
      BUILD_DIR: build-tests
      VENV_DIR: ${{ github.workspace }}/.venv
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@v4
      - name: "Checking out runtime submodules"
        run: ./build_tools/scripts/git/update_runtime_submodules.sh
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install cmake clang ninja-build
          export CC=clang
          export CXX=clang
      - name: "Setting up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Setup Python venv"
        run: python3 -m venv ${VENV_DIR}
      - name: "Installing IREE nightly release Python packages"
        run: |
          source ${VENV_DIR}/bin/activate
          python3 -m pip install \
            --find-links https://iree.dev/pip-release-links.html \
            iree-compiler iree-runtime
      - name: "Building tests"
        run: |
          source ${VENV_DIR}/bin/activate
          ./build_tools/pkgci/build_tests_using_package.sh ${VENV_DIR}/bin
      - name: "Running tests"
        env:
          IREE_EXTRA_COMMA_SEPARATED_CTEST_LABELS_TO_EXCLUDE: test-type=lit-test
        run: |
          source ${VENV_DIR}/bin/activate
          ./build_tools/cmake/ctest_all.sh ${BUILD_DIR}
