# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Workflow for running Examples of IREE usage against releases periodically.

name: samples

on:
  schedule:
    # Weekdays at 13:00 UTC = 05:00 PST / 06:00 PDT. No one should be dealing
    # with this on weekends.
    - cron: "5 4 * * 1-5"
  workflow_dispatch:

jobs:
  colab:
    runs-on: ubuntu-20.04-64core
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
      - name: "Testing Colab Notebooks"
        run: |
          ./build_tools/github_actions/docker_run.sh  \
            gcr.io/iree-oss/samples@sha256:b7d3bdb06666f848431fde350760b1c7f1bd89b8f3c27d97015c92d060f25d8d \
            ./samples/colab/test_notebooks.py

  samples:
    runs-on: ubuntu-20.04-64core
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
      - name: "Testing Samples"
        run: |
          ./build_tools/github_actions/docker_run.sh  \
            gcr.io/iree-oss/samples@sha256:b7d3bdb06666f848431fde350760b1c7f1bd89b8f3c27d97015c92d060f25d8d \
            ./build_tools/testing/test_samples.sh

  # FIXME: unify this with host build from ci.yml. This is complicated by
  # incompatibility between storage options for GitHub-managed and self-hosted
  # runners.
  web:
    runs-on: ubuntu-20.04-64core
    # TODO: remove dependence on magic matching build dir names
    env:
      HOST_BUILD_DIR: build-host-install
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
        with:
          submodules: true
      - name: "Building host tools"
        run: |
          ./build_tools/github_actions/docker_run.sh  \
            --env "CCACHE_NAMESPACE=gcr.io/iree-oss/base@sha256:988ef20f407c3a9af792f585ec92c7413777269ad4a5b5fa18e0f8a0d0fbf5e0" \
            gcr.io/iree-oss/base@sha256:988ef20f407c3a9af792f585ec92c7413777269ad4a5b5fa18e0f8a0d0fbf5e0 \
            ./build_tools/cmake/build_host_tools.sh "${HOST_BUILD_DIR}"
      - name: "Testing Experimental Web Samples"
        env:
          IREE_EMPSCRIPTEN_BUILD_DIR: build-emscripten
        run: |
          ./build_tools/github_actions/docker_run.sh  \
            --env "IREE_HOST_BUILD_DIR=${HOST_BUILD_DIR}" \
            --env "IREE_EMPSCRIPTEN_BUILD_DIR=${IREE_EMPSCRIPTEN_BUILD_DIR}" \
            gcr.io/iree-oss/emscripten@sha256:aaf8df29a1fd1adbec7a60f5964e383fcf268d57f3c740daf2915ed21e56edba \
            ./experimental/web/build_and_test_samples.sh
