# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Test Package

on:
  pull_request:
  workflow_dispatch:

  # TODO(scotttodd): input for release tag or artifact location
    # inputs:
    #   release_id:
    #     description: "Release id to publish"
    #     required: true
    #   package_version:
    #     description: "Version of the package"
    #     required: true
    #   build_run_id:
    #     description: "Run ID for the build_package.yml workflow that triggered this workflow"
    #     required: true

# TODO(scotttodd): switch to runtime submodules only
#   * Use a Docker image with `lit` installed (`python -m pip install lit`)
#   * `run: ./build_tools/scripts/git/update_runtime_submodules.sh`

jobs:
  linux_x86_64_cpu:
    name: Test on Linux (x86_64) CPU
    runs-on: ubuntu-20.04
    # container: gcr.io/iree-oss/base@sha256:61e9aae211007dbad95e1f429e9e5121fd5968c204791038424979c21146cf75
    # container:
    #   image: docker://ghcr.io/nod-ai/manylinux_x86_64:main
    #   options: --user 1001
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        # with:
        #   submodules: true
      - name: "Checking out runtime submodules"
        run: ./build_tools/scripts/git/update_runtime_submodules.sh
      - name: "Downloading release package"
        uses: robinraju/release-downloader@368754b9c6f47c345fcfbf42bcb577c2f0f5f395 # v1.9
        with:
          repository: "openxla/iree"
          tag: "candidate-20240131.787"
          # TODO(scotttodd): infer filename if possible / get from inputs
          fileName: "iree-dist-20240131.787-linux-x86_64.tar.xz"
      - name: "Extracting package archive"
        run: |
          mkdir iree-dist
          tar -xf "iree-dist-20240131.787-linux-x86_64.tar.xz" -C "iree-dist"
      - name: "Building tests"
        uses: docker://gcr.io/iree-oss/base@sha256:61e9aae211007dbad95e1f429e9e5121fd5968c204791038424979c21146cf75
        # uses: docker://ghcr.io/nod-ai/manylinux_x86_64:main
        with:
          args: bash ./build_tools/pkgci/build_tests_using_package.sh iree-dist
        # run: bash ./build_tools/pkgci/build_tests_using_package.sh iree-dist
      - name: "Testing package"
        run: ./build_tools/pkgci/test_package.sh
